### ISSUE TITLE
Does not support Bootstrapping for .NET Core Tool out of box

### ISSUE THREAD

**Issue by DanFTRX** [cake-build/cake-vscode#409] opened 2020-09-23 19:03 UTC
The VSCode plugin does not support the new .NET Core Tool bootstrapper out of the box.  It still expects a ps1 file.  I was able to work around it by adding a ps1 file that just calls "dotnet cake" with the supplied arguments, but it would be nice for it to work out of the box.

**Comment by pascalberger** [comment] 2020-10-16 11:57
@gep13 Is this a duplicate of #376?

**Comment by nils-a** [comment] 2020-11-02 23:00
@pascalberger I *think* this is either about "Run Task"-command or about the CodeLens.

Both use either `build.ps1` or `build.sh`, depending on the os. 
* for "Run Task"-commands see https://github.com/cake-build/cake-vscode/blob/develop/src/cakeMain.ts#L164
* for CodeLens, see https://github.com/cake-build/cake-vscode/blob/develop/src/codeLens/cakeRunTaskCommand.ts#L11

So I think this is rather a duplicate of #143

**Comment by DanFTRX** [comment] 2020-11-03 14:22
Yeah sorry this is in regards to "Run Task"

**Closed** 2020-11-30 19:06 UTC
Labels: Improvement
