### ISSUE TITLE
Feature Request: Implement Code outline for cake scripts. 

### ISSUE THREAD

**Issue by Tdue21** [cake-build/cake-vscode#100] opened 2018-10-20 22:26 UTC
It would be great if the Code Outline feature of VS Code could be implemented in this addin. 
This way, it would be easy to navigate between tasks in a large script.

**Comment by patriksvensson** [comment] 2018-10-21 11:01
@Tdue21 Great idea! Is this something you would like to help out with?

**Comment by Tdue21** [comment] 2018-10-21 11:03
Oh, I would love to, but I know nothing about TypeScript or the VS Code domain model.

**Comment by patriksvensson** [comment] 2018-10-21 11:03
@Tdue21 No problem! Worth checking 😄

**Comment by Tdue21** [comment] 2018-10-21 11:04
Absolutely. I do think though that maybe it would a bit too heavy for a learning project :)

**Comment by pascalberger** [comment] 2018-10-21 11:05
Is this a duplicate of #99?

**Comment by Tdue21** [comment] 2018-10-21 11:09
No, although Breadcrumbs are cool too, they are two different features. See this for Outline:
https://code.visualstudio.com/updates/v1_25#_outline-view

**Comment by Tdue21** [comment] 2018-10-26 06:59
I am gonna take a stab at this. Seems like as good a starting place for learning TypeScript and the VSCode domain model as any :)

**Comment by gep13** [comment] 2018-10-26 07:14
@Tdue21 that is great news!  I haven't looked at this new API in VSCode yet, so I won't be in a position to give any direct guidance, but feel free to reach out and ask any questions that you might have.

**Comment by nils-a** [comment] 2020-11-16 09:49
Reading this, I feel @pascalberger is "sort of" correct. 

While this is technically not really a duplicate, both features require a  `DocumentSymbolProvider` and then they both work. 
The following is a screenshot I mad from my first stab at #99 :

![image](https://user-images.githubusercontent.com/349188/99237816-48674700-27f9-11eb-99d5-4dc09916d619.png)

So.. The same code will fix both issues.

**Comment by nils-a** [comment] 2020-11-16 15:03
@Tdue21 I realize this has been idling around for some time. Are you in a position and willing to rebase this PR? I'd really love to take it for a spin.

**Comment by gep13** [comment] 2020-11-16 20:51
@nils-a as mentioned in other issue, I think the best suggestion here would be to wait until Cake LSP implementation is available, which should make some of this work much easier to achieve.

**Comment by gep13** [comment] 2020-11-16 20:57
I am going to close this as a duplicate of this issue: https://github.com/cake-build/cake-vscode/issues/99

While breadcrumbs and code outline are two pieces of functionality within VSCode, they are both implemented by the creation of a DocumentSymbolProvider, so no need for two issues to track this feature.

**Closed by gep13** 2020-11-16 20:57 UTC
Labels: Feature
