### ISSUE TITLE
Cannot read property 'Tools' of undefined while trying to debug

### ISSUE THREAD

**Issue by Diogomrol** [cake-build/cake-vscode#308] opened 2020-01-13 14:14 UTC
Hi,

After installing the Cake extension it looks like the "debug task" helper cannot be used.

Anytime I click "debug task" I get a message saying **"Cannot read property 'Tools' of undefined"**.

If I try to do the debug using the Visual Studio Code debug window, I get another error trying to load Cake.Powershell lib.

`Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.9\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\svn\trunk\HubServer\BuildScripts\tools\Cake.CoreCLR\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\svn\trunk\HubServer\BuildScripts\tools\Cake.CoreCLR\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.9\System.IO.MemoryMappedFiles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Error: Cake.Core.CakeException: Failed to install addin 'Cake.Powershell'.
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection`1 addins, DirectoryPath installPath) in C:\projects\cake\src\Cake.Core\Scripting\ScriptProcessor.cs:line 114
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 152
   at Cake.Commands.DebugCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\DebugCommand.cs:line 50
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 73
The program '[94800] Cake.dll' has exited with code 1 (0x1).`

Are there any known limitations of the debug that might be causing this?

Thanks for the help!

**Comment by squideyes** [comment] 2020-01-21 19:03
I'm also experiencing this problem.  I thought it might be setup-dependent so I tried it on two separate machines but the issue occured

**Comment by lstefano71** [comment] 2020-01-31 10:30
Same problem here. Workaround: put the following in cake.config:
```
[Paths]
Tools=tools
```
Once you do that it'll stop complaining about the property of undefined. It still does not work on my machine but that may be something different. Good luck!

**Comment by lstefano71** [comment] 2020-01-31 15:42
I cannot get the codelens command "Debug Task" to work but I think I know why it does not work. First of all: this is under Windows because I suspect that in Linux or MacOS it works. 
The culprit seems to be this line: https://github.com/cake-build/cake-vscode/blob/cfebb270a251dd07cdb323c3a941bc7ecb80204f/src/codeLens/cakeDebugTask.ts#L28

The "target" parameter is put on the command line with escaped quotes. Windows does not like that. I tried to execute the final command built by composing the arguments and I got:  
```
C:\Users\stf>"C:\Program Files\dotnet\dotnet.exe" C:\Users\stf\source\repos\RCSServer\tools\Cake.CoreCLR\Cake.dll c:\Users\stf\source\repos\RCSServer\build.cake --target=\"TestConverter\" --debug --verbosity=normal
More than one build script specified.
For usage, use parameter --help
```
If I remove the backslashes, instead I get: 
```
C:\Users\stf>"C:\Program Files\dotnet\dotnet.exe" C:\Users\stf\source\repos\RCSServer\tools\Cake.CoreCLR\Cake.dll c:\Users\stf\source\repos\RCSServer\build.cake --target="TestConverter" --debug --verbosity=normal
Attach debugger to process 10356 to continue
```
Which seems to be the proper behaviour.
![image](https://user-images.githubusercontent.com/2143482/73552443-8f41a700-4448-11ea-86c7-3c9fa9282e40.png)

Given that it might depend on the OS (on the shell, more precisely) I don't dare offer a PR because I would not be able to test it on an OS different than Windows.

**Comment by lstefano71** [comment] 2020-01-31 16:59
Yes, I can confirm that the problem is those slashes before the quotes. But not those in the source code, unfortunately. For reasons I don't understand, `vscode.debug.startDebugging` puts a backslash before the quotes. And Windows (or is it dotnet.exe?) does not like that. If I change the line in the extension source code to be:
    `--target=${taskName}`
then the codelens command "Debug Task" works. But, I suppose, it'll only work for tasks whose name does not contain spaces.

**Comment by gep13** [comment] 2020-11-23 21:30
This came up during testing of the overall extension on the Twitch Stream on 23/11/2020, and hopefully this will be addressed before the next release.

**Comment by gep13** [comment] 2020-11-29 09:55
@lstefano71 this has been fixed, and will be addressed in the next release.

**Closed** 2020-11-29 09:54 UTC
Labels: Bug
