### ISSUE TITLE
"Configure Default Build Task" doesn't work with Cake

### ISSUE THREAD

**Issue by WalkerCodeRanger** [cake-build/cake-vscode#87] opened 2018-02-22 13:52 UTC
Normally, you can configure a default build task so that pressing `ctrl+shift+b` will immediately run the task. You can set this up by selecting from the command palette "Tasks: Configure Default Build Task". It will then give you a list of tasks it understands for you to pick from. Select "Cake: Default". This adds an entry to your `tasks.json` file. That entry is:

```json
{
	"type": "cake",
	"script": "Default",
	"group": {
		"kind": "build",
		"isDefault": true
	}
}
```
However, the console immediately shows the error:
```
Error: there is no registered task type 'cake'. Did you miss to install an extension that provides a corresponding task provider?
```
Now, pressing `ctrl+shift+b` opens a dropdown to select which task to run. I would expect it to run the configured task immediately without any prompting.  This is the behavior I get if I set up some other kind of tasks as my default build task.

**Comment by gep13** [comment] 2018-02-22 14:14
@WalkerCodeRanger can you help me understand what you are doing here?  Where are you finding the option to select `Cake: Default`?  I am not seeing that option.

**Comment by WalkerCodeRanger** [comment] 2018-02-22 16:17
Sorry, that was confusing. I have a task named "Default" in my cake build file. Just pick any cake task that you want to run as the default build task.

**Comment by nils-a** [comment] 2020-11-13 23:14
I can not reproduce that problem. I'm guessing  @gep13 fixed it in https://github.com/cake-build/cake-vscode/commit/5cd4777f30d09b8f21815b0a42f2351db5365968.

@WalkerCodeRanger Do you still have the problem?

**Comment by WalkerCodeRanger** [comment] 2020-11-15 17:49
I'm no longer using Cake so I can't say if the issue still exists or not.

**Comment by nils-a** [comment] 2020-11-15 19:57
@gep13 I'd vote to close this issue. I think the problem was fixed (see above) and I can no longer reproduce it.

**Closed** 2020-11-16 20:36 UTC
Labels: Improvement
