### ISSUE TITLE
Dotnet global tool support

### ISSUE THREAD

**Issue by n-sidorov** [cake-build/cake-vscode#104] opened 2018-11-12 15:22 UTC
Cake v0.30 introduced an ability to run scripts via `dotnet cake` (https://cakebuild.net/blog/#global-tool) without the need of `build.ps1`.

Cake VS Code extension currently has cool auto-discover functionality but it works only with `build.ps`.

Is there are any plans to support global dotnet tool in this scenario?

**Comment by DanFTRX** [comment] 2020-09-10 15:08
This would be nice.  I can no longer use this extension because FIPS compliance prevents using the build.ps1 bootstrapper.

**Comment by pascalberger** [comment] 2020-10-16 13:57
@gep13 Is this a duplicate of #376?

**Comment by gep13** [comment] 2020-11-16 20:50
@pascalberger yes, I think there are several overlapping issues here.  Let's go ahead and close this one out, in favour of the others that are actively being worked on.

**Closed by gep13** 2020-11-16 20:50 UTC
